version: "3.8"

services:
  notification_service:
    env_file:
      - .env
    container_name: notification_service
    build:
      context: ./notification_service
      dockerfile: Dockerfile
      args:
        - app_port=${NOTIFICATION_SERVICE_PORT}
    network_mode: host
    volumes:
      - ./notification_service:/app

    
    # depends_on:
    #   - rabbitmq

  user_service:
    env_file:
      - .env
    container_name: user_service
    build:
      context: ./users_service
      dockerfile: Dockerfile
      args:
        - app_port=${USER_SERVICE_PORT}
    network_mode: host
    volumes:
      - ./users_service:/app